using Ecommerce.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ecommerce.Infrastructure.Persistence.Configurations;

public class DeliveryAddressConfiguration : IEntityTypeConfiguration<DeliveryAddress>
{
    public void Configure(EntityTypeBuilder<DeliveryAddress> builder)
    {
        builder.ToTable("delivery_addresses");

        builder.HasKey(a => a.Id);

        // Generated by the application (UUID v7). Without this, an id that is already set is taken
        // for an existing row and EF issues an UPDATE that affects nothing.
        builder.Property(a => a.Id).ValueGeneratedNever();

        builder.Property(a => a.RecipientName).HasMaxLength(100).IsRequired();
        builder.Property(a => a.Line1).HasMaxLength(200).IsRequired();
        builder.Property(a => a.Line2).HasMaxLength(200);
        builder.Property(a => a.City).HasMaxLength(100).IsRequired();
        builder.Property(a => a.Region).HasMaxLength(100);
        builder.Property(a => a.PostalCode).HasMaxLength(16).IsRequired();
        builder.Property(a => a.Country).HasMaxLength(2).IsFixedLength().IsRequired();
        builder.Property(a => a.Phone).HasMaxLength(30);

        builder.HasIndex(a => a.UserId);

        // At most one default per customer, as a constraint and not only as code (constitution:
        // invariants that matter are expressed as database constraints as well).
        builder.HasIndex(a => a.UserId)
            .HasDatabaseName("ux_delivery_addresses_one_default_per_user")
            .IsUnique()
            .HasFilter("\"IsDefault\"");

        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(a => a.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
