using Ecommerce.Order.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ecommerce.Order.Infrastructure.Persistence.Configurations;

public class OrderShipmentConfiguration : IEntityTypeConfiguration<OrderShipment>
{
    public void Configure(EntityTypeBuilder<OrderShipment> builder)
    {
        builder.ToTable("order_shipments");

        builder.HasKey(x => x.Id);

        // Generated by the application, so a part staged through Order.Shipments is INSERTed rather
        // than taken for an existing row and UPDATEd into a concurrency exception (CLAUDE.md gotcha).
        builder.Property(x => x.Id).ValueGeneratedNever();

        builder.Property(x => x.Status)
            .HasConversion<string>()
            .HasMaxLength(16)
            .IsRequired();

        builder.Property(x => x.TrackingReference).HasMaxLength(100);

        builder.HasOne(x => x.Order)
            .WithMany(x => x.Shipments)
            .HasForeignKey(x => x.OrderId)
            .OnDelete(DeleteBehavior.Cascade);

        // ⚠️ NULLS NOT DISTINCT (specs/035 research D1). SellerId null is the shop's own part, and with
        // PostgreSQL's default two shop parts for one order would both be allowed - and the create-if-
        // missing statement, which relies on ON CONFLICT against this index, would add another every
        // time it ran.
        builder.HasIndex(x => new { x.OrderId, x.SellerId })
            .IsUnique()
            .AreNullsDistinct(false)
            .HasDatabaseName("IX_order_shipments_OrderId_SellerId");

        // A seller's sales and moves start from "parts of this seller".
        builder.HasIndex(x => x.SellerId);
    }
}
