using System.Runtime.CompilerServices;
using Ecommerce.Catalog.Application.Common.Interfaces;

namespace Ecommerce.Catalog.Infrastructure.Images;

/// <summary>
/// Product images as files in one directory - a named volume in containers (specs/019).
/// </summary>
/// <remarks>
/// <para>
/// <b>Assumes one Catalog instance.</b> A second would have its own directory and serve 404 for every
/// image the first one stored. Object storage behind <see cref="IProductImageStore"/> is the answer;
/// this is recorded, not solved.
/// </para>
/// <para>
/// Checked at construction, which <c>Program.cs</c> forces at startup: a root that cannot be created
/// or written stops the service, rather than surfacing as a 500 on the first upload.
/// </para>
/// </remarks>
public sealed class FileSystemProductImageStore : IProductImageStore
{
    private readonly string _root;

    /// <param name="probe">
    /// False only to READ an existing directory - the old volume the S3 import copies from (specs/079), mounted
    /// read-only, where a write probe would fail by design.
    /// </param>
    public FileSystemProductImageStore(string root, bool probe = true)
    {
        _root = Path.GetFullPath(root);

        if (!probe)
        {
            return;
        }

        try
        {
            Directory.CreateDirectory(_root);
            var probeFile = Path.Combine(_root, $".write-probe-{Guid.NewGuid():N}");
            File.WriteAllBytes(probeFile, []);
            File.Delete(probeFile);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            throw new InvalidOperationException(
                $"Product images cannot be stored: '{_root}' is not a writable directory. "
                + "Set ProductImages:Root to one that is (in containers, a volume the app user owns).", ex);
        }
    }

    public string Root => _root;

    public async Task SaveAsync(string key, ReadOnlyMemory<byte> content, CancellationToken cancellationToken = default)
    {
        var path = PathFor(key);
        var temp = path + $".{Guid.NewGuid():N}.tmp";

        // Written aside, then moved into place: a reader never sees half a file, and a failure leaves
        // no file under the real key.
        try
        {
            await File.WriteAllBytesAsync(temp, content.ToArray(), cancellationToken);
            File.Move(temp, path, overwrite: false);
        }
        finally
        {
            if (File.Exists(temp))
            {
                File.Delete(temp);
            }
        }
    }

    public Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = PathFor(key);

        try
        {
            // FileShare.Delete: a replacement may remove this version while it is being sent.
            Stream stream = new FileStream(path, FileMode.Open, FileAccess.Read,
                FileShare.Read | FileShare.Delete, bufferSize: 81920, useAsync: true);
            return Task.FromResult<Stream?>(stream);
        }
        catch (FileNotFoundException)
        {
            return Task.FromResult<Stream?>(null);
        }
    }

    public Task DeleteAsync(string key, CancellationToken cancellationToken = default)
    {
        File.Delete(PathFor(key));   // no error when it is already gone
        return Task.CompletedTask;
    }

    public async IAsyncEnumerable<StoredImage> ListAsync(
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        foreach (var path in Directory.EnumerateFiles(_root))
        {
            cancellationToken.ThrowIfCancellationRequested();

            var name = Path.GetFileName(path);

            // The write probe this class creates at construction, and anything else beginning with
            // a dot. It is not a product image; counting it as waste would be wrong and deleting it
            // as if the catalogue had lost it would be worse. Only the store knows what its own
            // bookkeeping looks like, which is why this exclusion lives here (specs/033 research D5).
            if (name.StartsWith('.'))
            {
                continue;
            }

            FileInfo info;
            try
            {
                info = new FileInfo(path);
                if (!info.Exists)
                {
                    continue;   // deleted between the enumeration and here; not an error
                }
            }
            catch (IOException)
            {
                continue;
            }

            yield return new StoredImage(name, info.Length, info.LastWriteTimeUtc);
        }

        await Task.CompletedTask;
    }

    /// <summary>
    /// Keys are generated by ProductImageKey, never taken from a request, but this is the one place a
    /// string becomes a path, so it refuses anything that could leave the root.
    /// </summary>
    private string PathFor(string key)
    {
        ProductImageKeys.EnsureSafe(key);
        return Path.Combine(_root, key);
    }
}
