using System.Text.RegularExpressions;
using Ecommerce.Catalog.Application.Common.Interfaces;

namespace Ecommerce.Catalog.Infrastructure.Images;

/// <summary>
/// Product images as files in one directory - a named volume in containers (specs/019).
/// </summary>
/// <remarks>
/// <para>
/// <b>Assumes one Catalog instance.</b> A second would have its own directory and serve 404 for every
/// image the first one stored. Object storage behind <see cref="IProductImageStore"/> is the answer;
/// this is recorded, not solved.
/// </para>
/// <para>
/// Checked at construction, which <c>Program.cs</c> forces at startup: a root that cannot be created
/// or written stops the service, rather than surfacing as a 500 on the first upload.
/// </para>
/// </remarks>
public sealed partial class FileSystemProductImageStore : IProductImageStore
{
    private readonly string _root;

    public FileSystemProductImageStore(string root)
    {
        _root = Path.GetFullPath(root);

        try
        {
            Directory.CreateDirectory(_root);
            var probe = Path.Combine(_root, $".write-probe-{Guid.NewGuid():N}");
            File.WriteAllBytes(probe, []);
            File.Delete(probe);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            throw new InvalidOperationException(
                $"Product images cannot be stored: '{_root}' is not a writable directory. "
                + "Set ProductImages:Root to one that is (in containers, a volume the app user owns).", ex);
        }
    }

    public string Root => _root;

    public async Task SaveAsync(string key, ReadOnlyMemory<byte> content, CancellationToken cancellationToken = default)
    {
        var path = PathFor(key);
        var temp = path + $".{Guid.NewGuid():N}.tmp";

        // Written aside, then moved into place: a reader never sees half a file, and a failure leaves
        // no file under the real key.
        try
        {
            await File.WriteAllBytesAsync(temp, content.ToArray(), cancellationToken);
            File.Move(temp, path, overwrite: false);
        }
        finally
        {
            if (File.Exists(temp))
            {
                File.Delete(temp);
            }
        }
    }

    public Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default)
    {
        var path = PathFor(key);

        try
        {
            // FileShare.Delete: a replacement may remove this version while it is being sent.
            Stream stream = new FileStream(path, FileMode.Open, FileAccess.Read,
                FileShare.Read | FileShare.Delete, bufferSize: 81920, useAsync: true);
            return Task.FromResult<Stream?>(stream);
        }
        catch (FileNotFoundException)
        {
            return Task.FromResult<Stream?>(null);
        }
    }

    public Task DeleteAsync(string key, CancellationToken cancellationToken = default)
    {
        File.Delete(PathFor(key));   // no error when it is already gone
        return Task.CompletedTask;
    }

    /// <summary>
    /// Keys are generated by ProductImageKey, never taken from a request, but this is the one place a
    /// string becomes a path, so it refuses anything that could leave the root.
    /// </summary>
    private string PathFor(string key)
    {
        if (!SafeKey().IsMatch(key))
        {
            throw new ArgumentException($"'{key}' is not a product image key.", nameof(key));
        }

        return Path.Combine(_root, key);
    }

    [GeneratedRegex("^[a-z0-9]+-[0-9]+\\.(jpg|png|webp)$")]
    private static partial Regex SafeKey();
}
