using System.Text.RegularExpressions;

namespace Ecommerce.Catalog.Infrastructure.Images;

/// <summary>
/// The shape of a product image key, checked by every store before the key becomes a path or an object name.
/// </summary>
/// <remarks>
/// Keys are generated by <c>ProductImageKey</c>, never taken from a request - but a store is where a string meets the
/// disk or the bucket, so it refuses anything else. <c>{id}-{version}.{ext}</c>, optionally prefixed
/// <c>variant-</c> (specs/032): the prefix keeps a variant's image from colliding with its product's, since the first
/// variant of a product REUSES the product's id (specs/020). No slash, no dot segment, no traversal.
/// </remarks>
public static partial class ProductImageKeys
{
    [GeneratedRegex("^(variant-)?[a-z0-9]+-[0-9]+\\.(jpg|png|webp)$")]
    private static partial Regex SafeKey();

    public static bool IsSafe(string key) => SafeKey().IsMatch(key);

    public static void EnsureSafe(string key)
    {
        if (!IsSafe(key))
        {
            throw new ArgumentException($"'{key}' is not a product image key.", nameof(key));
        }
    }

    /// <summary>What an object is, for anybody who reads the bucket directly - Catalog itself decides by the bytes.</summary>
    public static string ContentType(string key) => Path.GetExtension(key) switch
    {
        ".jpg" => "image/jpeg",
        ".png" => "image/png",
        ".webp" => "image/webp",
        _ => "application/octet-stream",
    };
}
