info:
  name: get all stock
  type: http
  seq: 1

http:
  method: GET
  url: "{{baseUrl}}/api/stock?pageNumber=1&pageSize=20"
  params:
    - name: pageNumber
      value: "1"
      type: query
    - name: pageSize
      value: "20"
      type: query
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        test("status 200", function() {
          expect(res.status).to.equal(200);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  Public. Optional `sku` filter.
