namespace Ecommerce.Domain.Entities;

/// <summary>
/// Somewhere a customer has parcels sent. Owned by exactly one user; nobody else can read it.
/// </summary>
/// <remarks>
/// Orders never point at this row. At checkout Order takes a <b>copy</b>, so editing or deleting an
/// address later cannot move a parcel that was already sent (specs/011-order-shipping).
/// </remarks>
public class DeliveryAddress
{
    /// <summary>Generated by the application as UUID v7 (ADR-001), so mapped ValueGeneratedNever.</summary>
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string RecipientName { get; set; } = string.Empty;
    public string Line1 { get; set; } = string.Empty;
    public string? Line2 { get; set; }
    public string City { get; set; } = string.Empty;
    public string? Region { get; set; }
    public string PostalCode { get; set; } = string.Empty;

    /// <summary>ISO 3166-1 alpha-2, upper case.</summary>
    public string Country { get; set; } = string.Empty;

    public string? Phone { get; set; }

    /// <summary>Exactly one per customer who has any addresses - enforced by a partial unique index.</summary>
    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}
